export enum Stat {
  AbilityPower = "ability_power",
  Armor = "armor",
  ArmorPenetration = "armor_penetration",
  AttackDamge = "attack_damage",
  AttackSpeed = "attack_speed",
  CooldownReduction = "cooldown_reduction",
  CriticalStrikeChance = "critical_strike_chance",
  CriticalStrikeDamage = "critical_strike_damage",
  Energy = "energy",
  EnergyRegeneration = "energy_regeneration",
  HealAndShieldPower = "heal_and_shield_power",
  Health = "health",
  HealthRegeneration = 'health_regeneration',
  LifeSteal = "life_steal",
  MagicPenetration = "magic_penetration",
  MagicResistence = "magic_resistance",
  Mana = "mana",
  ManaRegeneration = 'mana_regeneration',
  MovementSpeed = "movement_speed",
  Omnivamp = "omnivamp",
  Range = "range",
  SlowInmune = "slow_immune",
  Tenacity = "tenacity",
}
